#!/usr/bin/env python3
"""Register batch-2 (subagent completion) sources. Run once."""
import subprocess
S = "/root/.hermes/skills/research/grounded-citations/scripts/sources.py"
URLS = [
 ("r/SaaS 3mo 868-50-5-0 funnel", "https://www.reddit.com/r/SaaS/comments/1s8c0e0/launched_my_saas_3_months_ago_still_no_paid_users"),
 ("IH DocBeacon <50 visitors 1 payer", "https://www.indiehackers.com/post/built-my-first-product-now-learning-the-hard-part-getting-users-68211f1c42"),
 ("HN no-demand vs no-exposure", "https://news.ycombinator.com/item?id=48942096"),
 ("r/microsaas first 10-100 PH150 fail", "https://www.reddit.com/r/microsaas/comments/1rbm61p/how_to_get_your_first_10100_saas_customers"),
 ("IH 1000lb club first 100", "https://www.indiehackers.com/post/how-i-got-my-first-100-users-2fc9d71c34"),
 ("Xenia PH 2 signups", "https://valishah.substack.com/p/what-launching-on-product-hunt-taught"),
 ("IH coding-easy-marketing-hard Piatra", "https://www.indiehackers.com/post/coding-is-easy-marketing-is-hard-lessons-from-a-dev-trying-to-build-products-7238fcd160"),
 ("IH 6 products 48h $0", "https://www.indiehackers.com/post/hot-take-building-products-is-the-easy-part-getting-anyone-to-look-is-the-whole-game-b6c23474f6"),
 ("IH DearFlow race did not start", "https://www.indiehackers.com/post/i-thought-the-hardest-part-was-building-the-product-i-was-wrong-a6bbb70ae4"),
 ("IH PostClaw 5 first users headline", "https://www.indiehackers.com/post/how-i-got-my-5-first-users-0e7d938186"),
 ("IH Jack Builds 0 to 47 paying", "https://www.indiehackers.com/post/i-spent-4-months-building-a-saas-that-got-0-signups-on-launch-day-heres-what-actually-worked-659a35f9e9"),
 ("IH Michii HN surprise buyers", "https://www.indiehackers.com/post/got-our-first-paid-customers-from-an-unexpected-channel-4a4067f803"),
 ("IH first-10-100-1000 compilation", "https://www.indiehackers.com/post/indie-hackers-share-how-they-got-their-first-10-100-and-1-000-customers-620ce768ba"),
 ("Plausible PH launch 2399-33", "https://plausible.io/blog/product-hunt-launch"),
 ("Alex Cloudstar distribution moat", "https://www.alexcloudstar.com/blog/building-is-easy-distribution-is-the-moat-2026"),
 ("saasconsult positioning mistakes", "https://saasconsult.co/blog/positioning-mistakes-saas-founders-make-and-how-to-fix-them"),
 ("Kalungi differentiate struggle", "https://www.kalungi.com/blog/why-saas-companies-struggle-to-differentiate"),
 ("IH automate-nothing-in-distribution", "https://www.indiehackers.com/post/the-indie-hackers-paradox-we-automate-everything-in-our-product-nothing-in-our-distribution-G8iXF3OkXiZMTxYSUCDi"),
 ("DEV Animiso landing AB 847-0", "https://dev.to/animiso_ce2f2f2e181032b7b/i-ab-tested-my-saas-landing-page-copy-heres-the-conversion-data-day-4-1ce6"),
 ("r/SaaS traffic-few-signups normal", "https://www.reddit.com/r/SaaS/comments/1mprsux/is_it_normal_to_get_traffic_but_few_signups_in_a/"),
 ("PH Lovable 850 paid turnaround", "https://www.producthunt.com/stories/initially-failed-ph-launch-turned-around-to-get-us-850-paid-subscribers"),
 ("GrowSurf churn 7-12 to 3-4", "https://kevinyun.substack.com/p/how-we-reduced-churn-by-200-for-our"),
 ("IH StatusPage renewal-reminder bug", "https://www.indiehackers.com/post/132-users-3-current-customers-and-a-renewal-failure-i-should-have-prevented-bf0d34a13f"),
 ("IH 6K MRR stall habit churn", "https://www.indiehackers.com/post/my-saas-hit-6k-mrr-then-immediately-stalled-the-problem-wasnt-my-product-ae8c24ce0d"),
 ("IH Featly PostHog-why gap", "https://www.indiehackers.com/post/i-talked-to-saas-founders-about-feature-usage-heres-what-they-all-said-e6d3d09ca1"),
 ("r/SaaS 14 feature requests decide", "https://www.reddit.com/r/SaaS/comments/1t0p5vh/how_do_you_actually_decide_which_feature_requests/"),
 ("Landon Bennett loud-customer trap", "https://medium.com/learning-how-to-saas/the-challenges-of-managing-user-feedback-at-an-early-stage-saas-startup-1bf70e53381b"),
 ("Cole Caccamise ICP sprawl cut", "https://colecaccamise.com/letters/prioritize-building-features"),
 ("Churn Buster 100 micro-decisions", "https://garrettdimon.com/starting-and-sustaining/interviews/matt-goldman"),
 ("Plink manual everything solo", "https://scottmathson.com/blog/2019/06/06/moving-beyond-mvp-saas-automation-onboarding-support-solo-founder/"),
 ("HN hidden work launching SaaS", "https://news.ycombinator.com/item?id=16360890"),
 ("r/SaaS churn afterthought", "https://www.reddit.com/r/SaaS/comments/1npx08f/churn_was_always_an_afterthought_in_my_startup"),
 ("r/SaaS 8.2K MRR exit repricing", "https://www.reddit.com/r/SaaS/comments/1mn0eo9/bootstrapped_a_tiny_saas_and_finally_sold_feels"),
 ("IH Evidio 15min-ticket context", "https://www.indiehackers.com/post/got-sick-of-tab-switching-for-support-tickets-so-im-building-evidio-bLyvZStND6YPe4nMNsfn"),
 ("IH LujanDev 40-to-8 proactive", "https://www.indiehackers.com/post/i-went-from-40-support-tickets-month-to-8-by-stopping-the-question-before-it-was-asked-e2c72fc877"),
 ("Storemapper solo support system", "https://tylertringas.com/customer-support-for-solo-founders"),
 ("XPilot zero-employee ops n8n", "https://dev.to/alexcloudstar/the-zero-employee-ops-team-how-i-automated-every-non-coding-task-in-my-solo-saas-1mmk"),
 ("Yaro founder burnout launch", "https://yaro.blog/founder-burnout/"),
 ("Micro-SaaS Insider fragmentation", "https://microsaasinsider.com/micro-saas-customer-support-solo-founder"),
 ("r/SaaS DM-drowning founder", "https://www.reddit.com/r/SaaS/comments/1pq4qx6/i_love_my_users_buthow_do_i_stop_getting_messages/"),
 ("r/microsaas inbox-chaos bot 80pct", "https://www.reddit.com/r/microsaas/comments/1omfcgh/our_support_inbox_used_to_be_chaos/"),
 ("r/SaaS burnout biggest threat", "https://www.reddit.com/r/SaaS/comments/1rwxy3a/unpopular_opinion_the_biggest_threat_to_your_saas/"),
 ("Docsio KB cuts tickets 40-60", "https://docsio.co/blog/saas-documentation"),
 ("IH TryEarn 5K Meta 150-CAC", "https://www.indiehackers.com/post/from-5000-wasted-on-meta-ads-to-200-users-in-2-days-at-2-user-here-s-how-i-did-it-9126899f51"),
 ("IH swipejuice 50K ads learnings", "https://www.indiehackers.com/post/what-i-learned-from-spending-50k-on-ads-30b9aff53b"),
 ("IH ColdCraft 23 days 8 signups", "https://www.indiehackers.com/post/23-days-of-distributing-a-saas-heres-exactly-what-happened-48bbe07158"),
 ("r/SaaS 1700 emails 5 clicks", "https://www.reddit.com/r/SaaS/comments/1ry5nrp/solo_founder_1700_cold_emails_5_clicks_0_signups/"),
 ("HN hannofcart no-ads-too-early", "https://news.ycombinator.com/item?id=37700847"),
 ("isora newsletter 750-0 sales", "https://isora.me/email-newsletter-sponsorship"),
 ("TeachShield SEO patience 30d", "https://teachshield.app/blog/seo-for-saas-what-actually-moves-the-needle"),
 ("r/SEO 4-5mo no traffic links", "https://www.reddit.com/r/SEO/comments/1q2s1o5/is_45_months_too_early_to_expect_seo_traffic_on_a/"),
 ("IH PostClaw 6-platform sludge", "https://www.indiehackers.com/post/i-post-on-6-platforms-i-never-open-one-09ce3a4392"),
 ("IH AdStake AI-Max drift", "https://www.indiehackers.com/post/we-caught-our-own-google-ads-account-wasting-money-twice-and-its-basically-been-our-whole-marketing-strategy-since-991b9e6d5a"),
 ("HN MealPrepPro 20K prereg waste", "https://news.ycombinator.com/item?id=36712564"),
 ("r/GrowthHacking 40 replies shift", "https://www.reddit.com/r/GrowthHacking/comments/1r31ntn/3_months_of_cold_outreach_with_almost_no_replies"),
 ("Marc Lou onboarding 95pct-4x", "https://newsletter.marclou.com/p/onboarding-is-killing-your-saas"),
 ("Flow turnaround transcript", "https://saasclub.io/podcast/flow-saas-turnaround-daniel-scrivner/"),
 ("IH better-activation not traffic", "https://www.indiehackers.com/post/you-dont-need-more-traffic-you-need-better-activation-QNyVJkq3lSJU044bHoFo"),
 ("DistributionBase ads-before-10K", "https://www.distributionbase.com/blog/playbooks/traction/why-paid-ads-fail-early"),
 ("ViSPR PH teardown 0 sales", "https://vispr.net/teardown-of-our-product-hunt-launch/"),
 ("HN PH launches-2x engagement-half", "https://news.ycombinator.com/item?id=48594670"),
 ("r/SaaS killed-trial rev-plus40", "https://www.reddit.com/r/SaaS/comments/1qnkfmb/the_saas_advice_that_keeps_killing_founders_made/"),
 ("IH onboarding 18-to-34 case", "https://www.indiehackers.com/post/how-an-onboarding-redesign-took-a-client-from-18-to-34-trial-to-paid-10be41f87b"),
 ("PostHog overkill solos thread", "https://www.reddit.com/r/micro_saas/comments/1thmkmx/posthog_is_overkill_analytics_for_solo_founders/"),
 ("HN Mixpanel pricing pain", "https://news.ycombinator.com/item?id=8381368"),
 ("Plausible-vs-GA thin thread", "https://www.reddit.com/r/analytics/comments/1n1ovkm/plausible_vs_google_analytics/"),
 ("Intercom alternatives thread", "https://www.reddit.com/r/SaaS/comments/1s8l1vl/what_are_bootstrapped_saas_teams_using_instead_of/"),
 ("Crisp-vs-Intercom thread", "https://www.reddit.com/r/SaaS/comments/wm6gw0/allinone_intercom_alternatives/"),
 ("HelpScout-to-HubSpot migrate", "https://www.reddit.com/r/hubspot/comments/1ehl0ei/migrating_successsupport_from_helpscout_to/"),
 ("Mailchimp unsubscribed billing", "https://www.reddit.com/r/indiehackers/comments/1p8p40k/mailchimp_was_charging_me_for_4000_unsubscribed/"),
 ("Customer.io scream thread", "https://www.reddit.com/r/Emailmarketing/comments/1nii0pq/if_you_use_customerio_userlist_encharge_whats_the/"),
 ("Loops review young limits", "https://www.promptstoproduct.com/loops-review"),
 ("Webflow CMS limits hike", "https://www.reddit.com/r/webflow/comments/1hgdbu6/webflow_cms_item_threshold_is_not_enough_now_what/"),
 ("Framer SEO nightmare", "https://www.reddit.com/r/framer/comments/1qbip8x/framer_is_an_seo_nightmare/"),
 ("Ahrefs 19-dollar alternative", "https://www.reddit.com/r/localseo/comments/1sdu6bo/built_a_19mo_alternative_to_ahrefs_and_semrush/"),
 ("Bye Semrush 8 years", "https://www.reddit.com/r/SEO/comments/1q4lq2k/bye_semrush_after_8_years_cutting_the_cord/"),
 ("Buffer posting bugs", "https://www.reddit.com/r/SocialMediaManagers/comments/1s3uhl2/issues_with_postingdownloading_media_from_buffer/"),
 ("Hypefury 6mo plateau", "https://www.reddit.com/r/AIToolTesting/comments/1kfazie/my_6month_experience_with_hypefury_ai_a_honest/"),
 ("Meta 175 CPM complaint", "https://www.reddit.com/r/FacebookAds/comments/1reksq8/over_5m_audience_but_meta_is_charging_me_175_per/"),
 ("PH total flop thread", "https://www.reddit.com/r/indiehackers/comments/1n83fu2/launched_on_product_hunt_total_flop_heres_what_i/"),
 ("BetaList worth-it 2021", "https://www.reddit.com/r/Entrepreneur/comments/o8zqcy/is_launching_on_betalist_worth_it_in_2021/"),
 ("Upwork getting worse", "https://www.reddit.com/r/Entrepreneur/comments/1lrg52s/upwork_is_getting_worse/"),
 ("Fiverr quality-vs-rating", "https://www.reddit.com/r/Fiverr/comments/133mc2g/advice_quality_low_but_feedback_high/"),
]
ok = fail = 0
for title, url in URLS:
    r = subprocess.run(["python3", S, "add", url, "--title", title],
                       capture_output=True, text=True)
    if r.returncode == 0:
        ok += 1
    else:
        fail += 1
        print("FAIL", url, r.stderr[-200:])
print(f"registered {ok}, failed {fail}")
